version: "3"
services:
  php:
    build: .
    container_name: "veiculos"
    image: php:8.1.16-apache
    volumes:
      - ./codigo/:/var/www/html/
    ports:
      - 8080:80
  db:
    image: mariadb:10.5
    container_name: "mariadb-veiculos"
    restart: always
    volumes:
      - ./banco/db_veiculos.sql:/docker-entrypoint-initdb.d/db_veiculos.sql
    environment:
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=321
  adminer:
    image: adminer:4.8.1
    container_name: "adminer-veiculos"
    restart: always
    ports:
      - 81:8080