USE veiculosbd;
INSERT INTO tb_cliente (nome, endereco, telefone) VALUES ( 'pedro', 'rua1', '4547');
INSERT INTO tb_cliente (nome, endereco, telefone) VALUES ( 'carlos', 'rua2', '4548');
INSERT INTO tb_cliente (nome, endereco, telefone) VALUES ( 'debora', 'rua3', '4549');
INSERT INTO tb_cliente (nome, endereco, telefone) VALUES ( 'deborah', 'rua4', '4540');
INSERT INTO tb_cliente (nome, endereco, telefone) VALUES ( 'davi', 'rua5', '4541');
INSERT INTO tb_cliente (nome, endereco, telefone) VALUES ( 'luis', 'rua6', '4542');
INSERT INTO tb_cliente (nome, endereco, telefone) VALUES ( 'gustavo', 'rua7', '4543');
INSERT INTO tb_cliente (nome, endereco, telefone) VALUES ( 'lucas', 'rua8', '4544');
INSERT INTO tb_cliente (nome, endereco, telefone) VALUES ( 'joao', 'rua9', '4545');
INSERT INTO tb_cliente (nome, endereco, telefone) VALUES ( 'paulo', 'rua10', '4546');
INSERT INTO tb_cliente (nome, endereco, telefone) VALUES ( 'TecnoSolucões', 'rua88', '351214567880');
INSERT INTO tb_cliente (nome, endereco, telefone) VALUES ( 'BioSaúde', 'rua11', '351214567890');
INSERT INTO tb_cliente (nome, endereco, telefone) VALUES ( 'Joana', 'rua11', '4547');
INSERT INTO tb_cliente (nome, endereco, telefone) VALUES ( 'Valdirene', 'rua12', '4548');
INSERT INTO tb_cliente (nome, endereco, telefone) VALUES ( 'Renata', 'rua13', '4549');
INSERT INTO tb_cliente (nome, endereco, telefone) VALUES ( 'Luiza', 'rua14', '5540');
INSERT INTO tb_cliente (nome, endereco, telefone) VALUES ( 'Marcia', 'rua15', '5541');
INSERT INTO tb_cliente (nome, endereco, telefone) VALUES ( 'Vera', 'rua16', '5542');
INSERT INTO tb_cliente (nome, endereco, telefone) VALUES ( 'Maria', 'rua17', '5543');

INSERT INTO tb_pessoafisica (cpf_pessoa, tb_cliente_id_cliente) VALUES ('534346465454', '1');
INSERT INTO tb_pessoafisica (cpf_pessoa, tb_cliente_id_cliente) VALUES ('634346465454', '2');
INSERT INTO tb_pessoafisica (cpf_pessoa, tb_cliente_id_cliente) VALUES ('734346465454', '3');
INSERT INTO tb_pessoafisica (cpf_pessoa, tb_cliente_id_cliente) VALUES ('834346465454', '4');
INSERT INTO tb_pessoafisica (cpf_pessoa, tb_cliente_id_cliente) VALUES ('934346465454', '5');
INSERT INTO tb_pessoafisica (cpf_pessoa, tb_cliente_id_cliente) VALUES ('534346465454', '6');
INSERT INTO tb_pessoafisica (cpf_pessoa, tb_cliente_id_cliente) VALUES ('434346465454', '7');
INSERT INTO tb_pessoafisica (cpf_pessoa, tb_cliente_id_cliente) VALUES ('334346465454', '8');
INSERT INTO tb_pessoafisica (cpf_pessoa, tb_cliente_id_cliente) VALUES ('234346465454', '9');
INSERT INTO tb_pessoafisica (cpf_pessoa, tb_cliente_id_cliente) VALUES ('134346465454', '10');
INSERT INTO tb_pessoafisica (cpf_pessoa, tb_cliente_id_cliente) VALUES ('514346465454', '11');
INSERT INTO tb_pessoafisica (cpf_pessoa, tb_cliente_id_cliente) VALUES ('534346465454', '12');
INSERT INTO tb_pessoafisica (cpf_pessoa, tb_cliente_id_cliente) VALUES ('524346465454', '13');
INSERT INTO tb_pessoafisica (cpf_pessoa, tb_cliente_id_cliente) VALUES ('544346465454', '14');
INSERT INTO tb_pessoafisica (cpf_pessoa, tb_cliente_id_cliente) VALUES ('554346465454', '15');
INSERT INTO tb_pessoafisica (cpf_pessoa, tb_cliente_id_cliente) VALUES ('564346465454', '16');
INSERT INTO tb_pessoafisica (cpf_pessoa, tb_cliente_id_cliente) VALUES ('574346465454', '17');
INSERT INTO tb_pessoafisica (cpf_pessoa, tb_cliente_id_cliente) VALUES ('584346465454', '18');
INSERT INTO tb_pessoafisica (cpf_pessoa, tb_cliente_id_cliente) VALUES ('594346465454', '19');
INSERT INTO tb_pessoafisica (cpf_pessoa, tb_cliente_id_cliente) VALUES ('589346465454', '20');

INSERT INTO tb_empresa (cnpj_empresa, tb_cliente_id_cliente) VALUES ( '24.567.891/0001-23', '1');
INSERT INTO tb_empresa (cnpj_empresa, tb_cliente_id_cliente) VALUES ( '24.567.891/0001-23', '22');
INSERT INTO tb_empresa (cnpj_empresa, tb_cliente_id_cliente) VALUES ( '34.567.891/0001-23', '23');
INSERT INTO tb_empresa (cnpj_empresa, tb_cliente_id_cliente) VALUES ( '44.567.891/0001-23', '24');
INSERT INTO tb_empresa (cnpj_empresa, tb_cliente_id_cliente) VALUES ( '54.567.891/0001-23', '25');
INSERT INTO tb_empresa (cnpj_empresa, tb_cliente_id_cliente) VALUES ( '64.567.891/0001-23', '26');
INSERT INTO tb_empresa (cnpj_empresa, tb_cliente_id_cliente) VALUES ( '74.567.891/0001-23', '27');
INSERT INTO tb_empresa (cnpj_empresa, tb_cliente_id_cliente) VALUES ( '84.567.891/0001-23', '28');
INSERT INTO tb_empresa (cnpj_empresa, tb_cliente_id_cliente) VALUES ( '94.567.891/0001-23', '29');
INSERT INTO tb_empresa (cnpj_empresa, tb_cliente_id_cliente) VALUES ( '24.167.891/0001-23', '30');
INSERT INTO tb_empresa (cnpj_empresa, tb_cliente_id_cliente) VALUES ( '24.267.891/0001-23', '31');
INSERT INTO tb_empresa (cnpj_empresa, tb_cliente_id_cliente) VALUES ( '24.367.891/0001-23', '32');
INSERT INTO tb_empresa (cnpj_empresa, tb_cliente_id_cliente) VALUES ( '24.467.891/0001-23', '33');
INSERT INTO tb_empresa (cnpj_empresa, tb_cliente_id_cliente) VALUES ( '24.557.891/0001-23', '34');
INSERT INTO tb_empresa (cnpj_empresa, tb_cliente_id_cliente) VALUES ( '24.667.891/0001-23', '35');
INSERT INTO tb_empresa (cnpj_empresa, tb_cliente_id_cliente) VALUES ( '24.767.891/0001-23', '36');
INSERT INTO tb_empresa (cnpj_empresa, tb_cliente_id_cliente) VALUES ( '24.867.891/0001-23', '37');
INSERT INTO tb_empresa (cnpj_empresa, tb_cliente_id_cliente) VALUES ( '24.967.891/0001-23', '38');
INSERT INTO tb_empresa (cnpj_empresa, tb_cliente_id_cliente) VALUES ( '24.268.891/0001-23', '39');
INSERT INTO tb_empresa (cnpj_empresa, tb_cliente_id_cliente) VALUES ( '24.568.191/0001-23', '40');

INSERT INTO tb_funcionario (nome_funcionario, cpf_funcionario, email_funcionario, telefone_funcionario) VALUES ( 'João', '112151515', 'joao@gmail.com', '25265464');
INSERT INTO tb_funcionario (nome_funcionario, cpf_funcionario, email_funcionario, telefone_funcionario) VALUES ('Carlos', '987654321', 'carlos@email.com', '99887766');
INSERT INTO tb_funcionario (nome_funcionario, cpf_funcionario, email_funcionario, telefone_funcionario) VALUES ('Larissa', '654321987', 'larissa@email.com', '55443322');
INSERT INTO tb_funcionario (nome_funcionario, cpf_funcionario, email_funcionario, telefone_funcionario) VALUES ('Fernando', '123789456', 'fernando@email.com', '66778899');
INSERT INTO tb_funcionario (nome_funcionario, cpf_funcionario, email_funcionario, telefone_funcionario) VALUES ('Juliana', '456123789', 'juliana@email.com', '77665544');
INSERT INTO tb_funcionario (nome_funcionario, cpf_funcionario, email_funcionario, telefone_funcionario) VALUES ('Paulo', '789456123', 'paulo@email.com', '88992233');
INSERT INTO tb_funcionario (nome_funcionario, cpf_funcionario, email_funcionario, telefone_funcionario) VALUES ('Patrícia', '321456987', 'patricia@email.com', '33445566');
INSERT INTO tb_funcionario (nome_funcionario, cpf_funcionario, email_funcionario, telefone_funcionario) VALUES ('Rodrigo', '654987321', 'rodrigo@email.com', '11223344');
INSERT INTO tb_funcionario (nome_funcionario, cpf_funcionario, email_funcionario, telefone_funcionario) VALUES ('Vanessa', '987321654', 'vanessa@email.com', '99887711');
INSERT INTO tb_funcionario (nome_funcionario, cpf_funcionario, email_funcionario, telefone_funcionario) VALUES ('Marcelo', '321789654', 'marcelo@email.com', '88776655');
INSERT INTO tb_funcionario (nome_funcionario, cpf_funcionario, email_funcionario, telefone_funcionario) VALUES ('Mariana', '654789321', 'mariana@email.com', '55446699');
INSERT INTO tb_funcionario (nome_funcionario, cpf_funcionario, email_funcionario, telefone_funcionario) VALUES ('Rafael', '987654123', 'rafael@email.com', '66778811');
INSERT INTO tb_funcionario (nome_funcionario, cpf_funcionario, email_funcionario, telefone_funcionario) VALUES ('Amanda', '123987456', 'amanda@email.com', '99886677');
INSERT INTO tb_funcionario (nome_funcionario, cpf_funcionario, email_funcionario, telefone_funcionario) VALUES ('Guilherme', '456789321', 'guilherme@email.com', '88776633');
INSERT INTO tb_funcionario (nome_funcionario, cpf_funcionario, email_funcionario, telefone_funcionario) VALUES ('Luiza', '789321456', 'luiza@email.com', '55449966');
INSERT INTO tb_funcionario (nome_funcionario, cpf_funcionario, email_funcionario, telefone_funcionario) VALUES ('Felipe', '321654789', 'felipe@email.com', '66771122');
INSERT INTO tb_funcionario (nome_funcionario, cpf_funcionario, email_funcionario, telefone_funcionario) VALUES ('Isabela', '654123987', 'isabela@email.com', '99882233');
INSERT INTO tb_funcionario (nome_funcionario, cpf_funcionario, email_funcionario, telefone_funcionario) VALUES ('Renato', '987456321', 'renato@email.com', '88771144');
INSERT INTO tb_funcionario (nome_funcionario, cpf_funcionario, email_funcionario, telefone_funcionario) VALUES ('Cristina', '123456789', 'cristina@email.com', '55442266');
INSERT INTO tb_funcionario (nome_funcionario, cpf_funcionario, email_funcionario, telefone_funcionario) VALUES ('Robertim', '123456759', 'robertim@email.com', '55442266');

INSERT INTO tb_veiculo (tipo_veiculo, placa_veiculo, capacidade_veiculo, vidroeletrico_veiculo, airbag_veiculo, capacidaportamala_veiculo, arcondicionado_veiculo, automatico_veiculo, km_veiculo, km_veiculofinal) VALUES ('honda-civic', 'br451l', '5', 'sim', 'sim', '10malas', 'sim', 'sim', '450', '550');
INSERT INTO tb_veiculo (tipo_veiculo, placa_veiculo, capacidade_veiculo, vidroeletrico_veiculo, airbag_veiculo, capacidaportamala_veiculo, arcondicionado_veiculo, automatico_veiculo, km_veiculo, km_veiculofinal) VALUES ('Toyota-Corolla', 'xyz9876', '5', 'sim', 'sim', '400L', 'sim', 'sim', '7000', '8000');
INSERT INTO tb_veiculo (tipo_veiculo, placa_veiculo, capacidade_veiculo, vidroeletrico_veiculo, airbag_veiculo, capacidaportamala_veiculo, arcondicionado_veiculo, automatico_veiculo, km_veiculo, km_veiculofinal) VALUES ('Fiat-Palio', 'uvw5432', '5', 'sim', 'não', '200L', 'sim', 'não', '4000', '5000');
INSERT INTO tb_veiculo (tipo_veiculo, placa_veiculo, capacidade_veiculo, vidroeletrico_veiculo, airbag_veiculo, capacidaportamala_veiculo, arcondicionado_veiculo, automatico_veiculo, km_veiculo, km_veiculofinal) VALUES ('Hyundai-HB20', 'rst7890', '5', 'sim', 'sim', '300L', 'sim', 'sim', '6000', '7000');
INSERT INTO tb_veiculo (tipo_veiculo, placa_veiculo, capacidade_veiculo, vidroeletrico_veiculo, airbag_veiculo, capacidaportamala_veiculo, arcondicionado_veiculo, automatico_veiculo, km_veiculo, km_veiculofinal) VALUES ('Renault-Sandero', 'pqr2468', '5', 'sim', 'não', '250L', 'sim', 'sim', '5500', '6500');
INSERT INTO tb_veiculo (tipo_veiculo, placa_veiculo, capacidade_veiculo, vidroeletrico_veiculo, airbag_veiculo, capacidaportamala_veiculo, arcondicionado_veiculo, automatico_veiculo, km_veiculo, km_veiculofinal) VALUES ('Chevrolet-Prisma', 'lmn1357', '5', 'sim', 'sim', '350L', 'sim', 'não', '7500', '8500');
INSERT INTO tb_veiculo (tipo_veiculo, placa_veiculo, capacidade_veiculo, vidroeletrico_veiculo, airbag_veiculo, capacidaportamala_veiculo, arcondicionado_veiculo, automatico_veiculo, km_veiculo, km_veiculofinal) VALUES ('Honda-Fit', 'abc2468', '5', 'sim', 'sim', '300L', 'sim', 'sim', '5000', '6000');
INSERT INTO tb_veiculo (tipo_veiculo, placa_veiculo, capacidade_veiculo, vidroeletrico_veiculo, airbag_veiculo, capacidaportamala_veiculo, arcondicionado_veiculo, automatico_veiculo, km_veiculo, km_veiculofinal) VALUES ('Nissan-Versa', 'def1357', '5', 'sim', 'não', '250L', 'sim', 'não', '4000', '5000');
INSERT INTO tb_veiculo (tipo_veiculo, placa_veiculo, capacidade_veiculo, vidroeletrico_veiculo, airbag_veiculo, capacidaportamala_veiculo, arcondicionado_veiculo, automatico_veiculo, km_veiculo, km_veiculofinal) VALUES ('Ford-EcoSport', 'ghi3691', '5', 'sim', 'sim', '350L', 'sim', 'sim', '6000', '7000');
INSERT INTO tb_veiculo (tipo_veiculo, placa_veiculo, capacidade_veiculo, vidroeletrico_veiculo, airbag_veiculo, capacidaportamala_veiculo, arcondicionado_veiculo, automatico_veiculo, km_veiculo, km_veiculofinal) VALUES ('Toyota-Hilux', 'jkl7531', '5', 'sim', 'sim', '500L', 'sim', 'sim', '8000', '9000');
INSERT INTO tb_veiculo (tipo_veiculo, placa_veiculo, capacidade_veiculo, vidroeletrico_veiculo, airbag_veiculo, capacidaportamala_veiculo, arcondicionado_veiculo, automatico_veiculo, km_veiculo, km_veiculofinal) VALUES ('hondias', 'br451l', '7', 'sim', 'sim', '10malas', 'sim', 'sim', '470', '770');
INSERT INTO tb_veiculo (tipo_veiculo, placa_veiculo, capacidade_veiculo, vidroeletrico_veiculo, airbag_veiculo, capacidaportamala_veiculo, arcondicionado_veiculo, automatico_veiculo, km_veiculo, km_veiculofinal) VALUES ('Toyotona', 'xyz9876', '7', 'sim', 'sim', '400L', 'sim', 'sim', '7000', '8000');
INSERT INTO tb_veiculo (tipo_veiculo, placa_veiculo, capacidade_veiculo, vidroeletrico_veiculo, airbag_veiculo, capacidaportamala_veiculo, arcondicionado_veiculo, automatico_veiculo, km_veiculo, km_veiculofinal) VALUES ('Fiat-Pa', 'uvw7432', '7', 'sim', 'não', '200L', 'sim', 'não', '4000', '7000');
INSERT INTO tb_veiculo (tipo_veiculo, placa_veiculo, capacidade_veiculo, vidroeletrico_veiculo, airbag_veiculo, capacidaportamala_veiculo, arcondicionado_veiculo, automatico_veiculo, km_veiculo, km_veiculofinal) VALUES ('Hy-HB20', 'rst7890', '7', 'sim', 'sim', '300L', 'sim', 'sim', '6000', '7000');
INSERT INTO tb_veiculo (tipo_veiculo, placa_veiculo, capacidade_veiculo, vidroeletrico_veiculo, airbag_veiculo, capacidaportamala_veiculo, arcondicionado_veiculo, automatico_veiculo, km_veiculo, km_veiculofinal) VALUES ('Renult-Sro', 'pqr2468', '7', 'sim', 'não', '270L', 'sim', 'sim', '7700', '6700');
INSERT INTO tb_veiculo (tipo_veiculo, placa_veiculo, capacidade_veiculo, vidroeletrico_veiculo, airbag_veiculo, capacidaportamala_veiculo, arcondicionado_veiculo, automatico_veiculo, km_veiculo, km_veiculofinal) VALUES ('Chevrosma', 'lmn1377', '7', 'sim', 'sim', '370L', 'sim', 'não', '7700', '8700');
INSERT INTO tb_veiculo (tipo_veiculo, placa_veiculo, capacidade_veiculo, vidroeletrico_veiculo, airbag_veiculo, capacidaportamala_veiculo, arcondicionado_veiculo, automatico_veiculo, km_veiculo, km_veiculofinal) VALUES ('Hondit', 'abc2468', '7', 'sim', 'sim', '300L', 'sim', 'sim', '7000', '6000');
INSERT INTO tb_veiculo (tipo_veiculo, placa_veiculo, capacidade_veiculo, vidroeletrico_veiculo, airbag_veiculo, capacidaportamala_veiculo, arcondicionado_veiculo, automatico_veiculo, km_veiculo, km_veiculofinal) VALUES ('Nisa', 'def1377', '7', 'sim', 'não', '270L', 'sim', 'não', '4000', '7000');
INSERT INTO tb_veiculo (tipo_veiculo, placa_veiculo, capacidade_veiculo, vidroeletrico_veiculo, airbag_veiculo, capacidaportamala_veiculo, arcondicionado_veiculo, automatico_veiculo, km_veiculo, km_veiculofinal) VALUES ('Forrt', 'ghi3691', '7', 'sim', 'sim', '370L', 'sim', 'sim', '6000', '7000');
INSERT INTO tb_veiculo (tipo_veiculo, placa_veiculo, capacidade_veiculo, vidroeletrico_veiculo, airbag_veiculo, capacidaportamala_veiculo, arcondicionado_veiculo, automatico_veiculo, km_veiculo, km_veiculofinal) VALUES ('Toyox', 'jkl7731', '7', 'sim', 'sim', '700L', 'sim', 'sim', '8000', '9000');